import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Kicker, Process, ServiceGrid } from '@/components/site/Marketing';
import creatorIllustration from '@/assets/tcma-creator-illustration.png';

export const Route = createFileRoute('/')({staticData:{sitemap:true},
 head:()=>({meta:[{title:'TCMA | Creator Marketing Agency for Consumer Brands'},{name:'description',content:'TCMA is a strategic creator marketing agency helping consumer brands grow through influencer marketing, UGC, and affiliate partnerships. Book a free strategy call.'},{property:'og:title',content:'TCMA | Creator Marketing Agency for Consumer Brands'},{property:'og:description',content:'Strategic creator marketing for consumer brands ready to grow.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}), component:Home
});
function Home(){return <main>
 <section className="bg-primary text-primary-foreground"><div className="mx-auto w-full max-w-5xl px-5 pt-10 pb-28 text-center md:pt-14 md:pb-36 lg:px-8 lg:pt-16 lg:pb-40"><p className="font-accent text-xl uppercase text-cream">The Creator Marketing Agency.</p><h1 className="mx-auto mt-5 max-w-5xl font-display text-6xl leading-[.95] text-cream md:text-8xl lg:text-9xl">We turn creators into growth channels.</h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-cream/80 md:text-lg">We build and manage creator programs that connect brands with the right creators, content, and partnerships to drive awareness, acquisition, and revenue. Data-informed strategy. Strong creator relationships. Measurable results.</p><div className="mt-9 flex justify-center"><Button asChild variant="secondary" size="lg"><Link to="/contact">Book a Free Strategy Call <ArrowRight/></Link></Button></div></div></section>
 <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 md:py-28 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><Kicker>What TCMA does</Kicker><img src={creatorIllustration} alt="Illustration of a creator filming with a phone and ring light" loading="lazy" width={1200} height={1200} className="mx-auto mt-7 w-full max-w-lg"/></div><div><h2 className="font-display text-5xl leading-tight md:text-7xl">Creators are more than media placements.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-muted-foreground">Most brands already work with creators in some form. Few have built a system around it. TCMA helps consumer brands turn scattered creator activity into a structured program — one that produces content, drives awareness, supports paid media, and connects to measurable growth. We work across four connected disciplines: creator partnerships, influencer marketing, UGC, and affiliate marketing — one creator ecosystem, not four separate services.</p></div></section>
 <section className="bg-cream"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><Kicker>What we do</Kicker><h2 className="mt-4 font-display text-5xl md:text-7xl">Four disciplines.<br/>One creator strategy.</h2></div><Link to="/services" className="flex items-center gap-2 font-accent text-lg uppercase text-primary">View all services <ArrowRight/></Link></div><ServiceGrid/></div></section>
 <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><Kicker>Why TCMA</Kicker><h2 className="mt-4 font-display text-5xl md:text-7xl">Why brands work with TCMA</h2><div className="mt-12 divide-y divide-border border-t border-border">{[['Strategic creator selection',"We don’t select creators by follower count. We look at audience fit, engagement quality, content style, and brand alignment first."],['Relationship-first partnerships','We build relationships designed to extend beyond a single post.'],['Performance mindset','Every creator activity is tied back to a business outcome, not just impressions.'],['Full-service execution',"You don’t need to manage five freelancers and three platforms. We run it as one process."],['Flexible creator access','We source creators across markets, niches, and audience sizes.']].map(([t,b],i)=><div key={t} className="grid gap-4 py-7 md:grid-cols-[80px_1fr_1fr]"><span className="font-accent text-xl text-primary">0{i+1}</span><h3 className="font-display text-2xl">{t}</h3><p className="leading-7 text-muted-foreground">{b}</p></div>)}</div></section>
 <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><p className="font-accent text-lg uppercase opacity-70">Creator Marketing Ecosystem</p><h2 className="mt-4 max-w-3xl font-display text-5xl md:text-7xl">One creator. Many stages of value.</h2><p className="mt-7 max-w-3xl text-lg leading-8 opacity-85">The strongest creator relationships don’t stay in one lane. A creator partnership can lead to product seeding, UGC, a paid campaign, affiliate partnership, and—over time—a long-term brand ambassador.</p><div className="mt-12 grid gap-px bg-primary-foreground/20 md:grid-cols-3 lg:grid-cols-7">{['Creator Partnership','Product Relationship','UGC Creation','Influencer Campaign','Affiliate Activation','Performance Data','Long-Term Ambassador'].map((x,i)=><div key={x} className="relative bg-primary px-5 py-7"><span className="font-accent text-sm opacity-60">0{i+1}</span><p className="mt-3 font-semibold">{x}</p></div>)}</div><p className="mt-10 font-display text-3xl">TCMA manages this as one system — not four disconnected services.</p></div></section>
 <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><Kicker>Our process</Kicker><h2 className="mt-4 mb-12 font-display text-5xl md:text-7xl">How we work</h2><Process/></section>
 <section className="border-y border-border bg-cream"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><Kicker>Industries</Kicker><div className="mt-4 grid gap-8 lg:grid-cols-2"><div><h2 className="font-display text-5xl">Who we work with</h2><p className="mt-5 max-w-lg leading-7 text-muted-foreground">TCMA works with consumer brands that have a strong product, an identifiable audience, and a real appetite for creator-led growth.</p></div><div className="flex flex-wrap content-start gap-3">{['Beauty','Skincare','Fashion','Lifestyle','E-commerce','Consumer Technology'].map(x=><span key={x} className="border border-primary px-5 py-3 font-accent text-xl uppercase text-primary">{x}</span>)}</div></div></div></section>
 <section className="bg-foreground text-background"><div className="mx-auto max-w-7xl px-5 py-20 text-center lg:px-8 lg:py-28"><h2 className="mx-auto max-w-4xl font-display text-5xl md:text-7xl">Ready to build a creator strategy that actually connects to growth?</h2><Button asChild size="lg" className="mt-9"><Link to="/contact">Book a Free Strategy Call <ArrowRight/></Link></Button></div></section>
 </main>}
