import { Link } from '@tanstack/react-router';
import { ArrowRight, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { processSteps, services, type Service } from '@/lib/site-data';

export function Kicker({children}:React.PropsWithChildren){return <p className="font-accent text-lg uppercase text-primary">{children}</p>}
export function PageHero({kicker,heading,body,children}:React.PropsWithChildren<{kicker:string;heading:string;body?:string}>){return <section className="bg-cream"><div className="mx-auto max-w-7xl px-5 py-20 md:py-28 lg:px-8"><Kicker>{kicker}</Kicker><h1 className="mt-5 max-w-5xl font-display text-5xl leading-[1.02] md:text-7xl lg:text-8xl">{heading}</h1>{body&&<p className="mt-7 max-w-3xl text-lg leading-8 text-muted-foreground md:text-xl">{body}</p>}{children&&<div className="mt-9">{children}</div>}</div></section>}
export function ServiceGrid(){return <div className="grid border-l border-t border-border md:grid-cols-2">{services.map(s=><Link key={s.slug} to={`/services/${s.slug}` as '/services/creator-partnerships'} className="group min-h-72 border-b border-r border-border bg-background p-7 transition-colors hover:bg-cream md:p-10"><span className="font-accent text-xl text-primary">{s.number}</span><h3 className="mt-12 font-display text-3xl md:text-4xl">{s.name}</h3><p className="mt-4 max-w-md leading-7 text-muted-foreground">{s.short}</p><ArrowRight className="mt-8 text-primary transition-transform group-hover:translate-x-1"/></Link>)}</div>}
export function Process(){return <div className="grid border-t border-border md:grid-cols-2 lg:grid-cols-3">{processSteps.map(([title,body],i)=><div key={title} className="border-b border-border py-8 md:px-6 md:first:pl-0 lg:border-r lg:px-8 lg:nth-[3n]:border-r-0"><span className="font-accent text-lg text-primary">0{i+1}</span><h3 className="mt-5 font-display text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p></div>)}</div>}
export function ServiceDetail({service}:{service:Service}){return <main><PageHero kicker={`Service ${service.number}`} heading={service.heading} body={service.body}><Button asChild size="lg"><Link to="/contact">{service.cta}<ArrowRight/></Link></Button></PageHero><section className="mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-[1fr_1.5fr] lg:px-8 lg:py-28"><div><Kicker>What this includes</Kicker><h2 className="mt-4 font-display text-4xl md:text-5xl">Built end to end.</h2></div><ul className="divide-y divide-border border-t border-border">{service.includes.map(x=><li key={x} className="flex items-center gap-4 py-5 text-lg"><Check className="size-5 text-primary"/>{x}</li>)}</ul></section><section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="font-accent text-lg uppercase opacity-70">Who this is for</p><p className="mt-5 max-w-5xl font-display text-3xl leading-tight md:text-5xl">{service.audience}</p></div></section><section className="mx-auto max-w-4xl px-5 py-20 lg:py-28"><Kicker>Frequently asked</Kicker><h2 className="mt-4 font-display text-5xl">The details.</h2><div className="mt-10 border-t border-border">{service.faqs.map((f,i)=><details key={f.q} className="group border-b border-border py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-semibold"><span>{f.q}</span><span className="font-accent text-2xl text-primary group-open:rotate-45">+</span></summary><p className="max-w-2xl pt-4 leading-7 text-muted-foreground">{f.a}</p></details>)}</div></section></main>}
