/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorNetworkRouteImport } from './routes/creator-network'
import { Route as ForBrandsRouteImport } from './routes/for-brands'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CreatorNetworkApplyRouteImport } from './routes/creator-network.apply'
import { Route as ServicesAffiliateMarketingRouteImport } from './routes/services.affiliate-marketing'
import { Route as ServicesCreatorPartnershipsRouteImport } from './routes/services.creator-partnerships'
import { Route as ServicesInfluencerMarketingRouteImport } from './routes/services.influencer-marketing'
import { Route as ServicesUgcMarketingRouteImport } from './routes/services.ugc-marketing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorNetworkRoute = CreatorNetworkRouteImport.update({
  id: '/creator-network',
  path: '/creator-network',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBrandsRoute = ForBrandsRouteImport.update({
  id: '/for-brands',
  path: '/for-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorNetworkApplyRoute = CreatorNetworkApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CreatorNetworkRoute,
} as any)
const ServicesAffiliateMarketingRoute =
  ServicesAffiliateMarketingRouteImport.update({
    id: '/affiliate-marketing',
    path: '/affiliate-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCreatorPartnershipsRoute =
  ServicesCreatorPartnershipsRouteImport.update({
    id: '/creator-partnerships',
    path: '/creator-partnerships',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesInfluencerMarketingRoute =
  ServicesInfluencerMarketingRouteImport.update({
    id: '/influencer-marketing',
    path: '/influencer-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesUgcMarketingRoute = ServicesUgcMarketingRouteImport.update({
  id: '/ugc-marketing',
  path: '/ugc-marketing',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/creator-network': typeof CreatorNetworkRouteWithChildren
  '/for-brands': typeof ForBrandsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/creator-network/apply': typeof CreatorNetworkApplyRoute
  '/services/affiliate-marketing': typeof ServicesAffiliateMarketingRoute
  '/services/creator-partnerships': typeof ServicesCreatorPartnershipsRoute
  '/services/influencer-marketing': typeof ServicesInfluencerMarketingRoute
  '/services/ugc-marketing': typeof ServicesUgcMarketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/creator-network': typeof CreatorNetworkRouteWithChildren
  '/for-brands': typeof ForBrandsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/creator-network/apply': typeof CreatorNetworkApplyRoute
  '/services/affiliate-marketing': typeof ServicesAffiliateMarketingRoute
  '/services/creator-partnerships': typeof ServicesCreatorPartnershipsRoute
  '/services/influencer-marketing': typeof ServicesInfluencerMarketingRoute
  '/services/ugc-marketing': typeof ServicesUgcMarketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/creator-network': typeof CreatorNetworkRouteWithChildren
  '/for-brands': typeof ForBrandsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/creator-network/apply': typeof CreatorNetworkApplyRoute
  '/services/affiliate-marketing': typeof ServicesAffiliateMarketingRoute
  '/services/creator-partnerships': typeof ServicesCreatorPartnershipsRoute
  '/services/influencer-marketing': typeof ServicesInfluencerMarketingRoute
  '/services/ugc-marketing': typeof ServicesUgcMarketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/creator-network'
    | '/for-brands'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/creator-network/apply'
    | '/services/affiliate-marketing'
    | '/services/creator-partnerships'
    | '/services/influencer-marketing'
    | '/services/ugc-marketing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/creator-network'
    | '/for-brands'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/creator-network/apply'
    | '/services/affiliate-marketing'
    | '/services/creator-partnerships'
    | '/services/influencer-marketing'
    | '/services/ugc-marketing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/creator-network'
    | '/for-brands'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/creator-network/apply'
    | '/services/affiliate-marketing'
    | '/services/creator-partnerships'
    | '/services/influencer-marketing'
    | '/services/ugc-marketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CreatorNetworkRoute: typeof CreatorNetworkRouteWithChildren
  ForBrandsRoute: typeof ForBrandsRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-network': {
      id: '/creator-network'
      path: '/creator-network'
      fullPath: '/creator-network'
      preLoaderRoute: typeof CreatorNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-brands': {
      id: '/for-brands'
      path: '/for-brands'
      fullPath: '/for-brands'
      preLoaderRoute: typeof ForBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-network/apply': {
      id: '/creator-network/apply'
      path: '/apply'
      fullPath: '/creator-network/apply'
      preLoaderRoute: typeof CreatorNetworkApplyRouteImport
      parentRoute: typeof CreatorNetworkRoute
    }
    '/services/affiliate-marketing': {
      id: '/services/affiliate-marketing'
      path: '/affiliate-marketing'
      fullPath: '/services/affiliate-marketing'
      preLoaderRoute: typeof ServicesAffiliateMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/creator-partnerships': {
      id: '/services/creator-partnerships'
      path: '/creator-partnerships'
      fullPath: '/services/creator-partnerships'
      preLoaderRoute: typeof ServicesCreatorPartnershipsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/influencer-marketing': {
      id: '/services/influencer-marketing'
      path: '/influencer-marketing'
      fullPath: '/services/influencer-marketing'
      preLoaderRoute: typeof ServicesInfluencerMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ugc-marketing': {
      id: '/services/ugc-marketing'
      path: '/ugc-marketing'
      fullPath: '/services/ugc-marketing'
      preLoaderRoute: typeof ServicesUgcMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface CreatorNetworkRouteChildren {
  CreatorNetworkApplyRoute: typeof CreatorNetworkApplyRoute
}

const CreatorNetworkRouteChildren: CreatorNetworkRouteChildren = {
  CreatorNetworkApplyRoute: CreatorNetworkApplyRoute,
}

const CreatorNetworkRouteWithChildren = CreatorNetworkRoute._addFileChildren(
  CreatorNetworkRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAffiliateMarketingRoute: typeof ServicesAffiliateMarketingRoute
  ServicesCreatorPartnershipsRoute: typeof ServicesCreatorPartnershipsRoute
  ServicesInfluencerMarketingRoute: typeof ServicesInfluencerMarketingRoute
  ServicesUgcMarketingRoute: typeof ServicesUgcMarketingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAffiliateMarketingRoute: ServicesAffiliateMarketingRoute,
  ServicesCreatorPartnershipsRoute: ServicesCreatorPartnershipsRoute,
  ServicesInfluencerMarketingRoute: ServicesInfluencerMarketingRoute,
  ServicesUgcMarketingRoute: ServicesUgcMarketingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CreatorNetworkRoute: CreatorNetworkRouteWithChildren,
  ForBrandsRoute: ForBrandsRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
